### PR TITLE
#89 Implement Notification Queue

### PR DESCRIPTION
**Pull request by theimo1221**
This implements Notification Queue and adds/extends some of the debug messages.

### CODE REVIEW

**Comment by theimo1221** [comment]
There are still two failures in Tests due to `FetchError: request to http://localhost:1400/MediaRenderer/RenderingControl/Control failed, reason: Nock: No match for request {` which unfortunately i wasn't able to resolve

**Comment by svrooij** [comment]
@theimo1221 I’m not sure if the event emitter was needed to play multiple notifications. What do you think about my version of the notification queue functionality? https://github.com/svrooij/node-sonos-ts/tree/feature/notification-queue

I’ve added a `callback` to the notification options. That allows you to know when the a specific notification has played. If I’m correct the signature or the PlayNotification isn’t changed. Only what it does. If you play only one notification nothing has changed. If you send an extra notification it returns immediately but the callback is called when the notification played.

In my application (sonos2mqtt) it doesn’t matter if a notification played. So it can just use the new functionality without a single change.

**Comment by theimo1221** [comment]
@svrooij As you said previously you worked hard to remove Callbacks. Plus your variant isn't backwards compatible (Timing of Promise Result) so personally I'd tend towards the method which resolves every Promise to `PlayNotification` based on the events.

**Comment by svrooij** [comment]
What is the use case for knowing if it actually played or when it played? I just need some context. I use this library mainly for sonos2mqtt and there it doesn't matter when or if they are played. It's just shoot and forget.

My version is perfectly backwards compatible. If you send one notification is executes the same requests and only returns when finished. And in the old version sending a second notification would break stuff and now just plays the notification.

Once you start queueing, in my opinion, the callback part fits better then the promise. (When you want to know if a single notification has played)

Why not use the
```javascript
return new Promise((resolve) => {
  // Play the specific notification
  resolve();
});
```

That allows you to turn something with a callback to a promise.

Using `setTimeout(...);` to trigger something in the background seems weird to me.

**Comment by theimo1221** [comment]
The use case is implementing fallback measurements
Like e.g. if I'm not able to tell the house alarm/notification then use a fallback channel like e.g. PushBullet

_Using setTimeout(...); to trigger something in the background seems weird to me._
It's a common way. Kinda like starting a task in a new thread.

Personally I don't mind using callbacks (actually I prefer it), but having both a promise and a callback makes it confusing, plus you might consider adding a separate callback for an error or including an error in the normal callback.

During implementation considering your feedback, you'd like to go without callbacks I first tried to gather some points why callbacks would be better here, but ended with several reasons why the solution without suits this library much better.

**Comment by svrooij** [comment]
Superceeded by #102

**Pull request closed without merging**
